/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Binary from 'react-native-binary';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };

  test = async () => {
    const fd = await Binary.open('/Users/nat/Desktop/rn.pcm').catch(err => console.log('open err', err))
    if(!fd) return console.log('OPen file failed')
    const data = await Binary.readAllAsFloat32Array(fd).catch(err => console.log('Read failed', err))
    this.setState({message: data.length})
    await Binary.close(fd)
  }

  componentDidMount() {
    this.test()
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Binary example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
